import React, { useState, useMemo } from "react";
import {
  X,
  FileText,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Award,
  BookOpen,
  Briefcase,
  Layers,
  Send,
  Calendar,
  Clock,
  User,
} from "lucide-react";
import { Applicant, InterviewComment } from "./ApplicantCard";

interface CandidateProfileModalProps {
  applicant: Applicant;
  currentUser: { name: string; email: string; role: string };
  onClose: () => void;
  onAddComment: (applicantId: string, commentText: string, author: string) => void;
  onSendInterview?: (id: string) => void;
  onRescindInterview?: (id: string) => void;
  onSendOffer?: (id: string) => void;
  onSendReject?: (id: string) => void;
  onUndoRejection?: (id: string) => void;
  onUpdateScheduledTimes?: (id: string, primaryTime: string | null, fallbackTime: string | null) => void;
}

function getDriveEmbedUrl(url?: string): string | null {
  if (!url) return null;
  const trimmed = url.trim();
  if (!trimmed || trimmed === "https://drive.google.com" || trimmed === "https://drive.google.com/") {
    return null;
  }

  // Handle the "open?id=..." format generated by Google Forms / Apps Script
  if (trimmed.includes("open?id=")) {
    const fileId = trimmed.split("open?id=")[1].split("&")[0];
    return `https://drive.google.com/file/d/${fileId}/preview`;
  }

  // Handle standard Google Drive view links (/file/d/ID/...)
  if (trimmed.includes("/file/d/")) {
    const fileId = trimmed.split("/file/d/")[1].split("/")[0];
    return `https://drive.google.com/file/d/${fileId}/preview`;
  }

  // If it's another direct URL, return as is
  return trimmed;
}

export default function CandidateProfileModal({
  applicant,
  currentUser,
  onClose,
  onAddComment,
  onSendInterview,
  onRescindInterview,
  onSendOffer,
  onSendReject,
  onUndoRejection,
  onUpdateScheduledTimes,
}: CandidateProfileModalProps) {
  const [commentText, setCommentText] = useState("");
  const [zoom, setZoom] = useState(100);
  const [showEssay, setShowEssay] = useState(false);
  const [isEditingTimes, setIsEditingTimes] = useState(false);
  const [primaryTimeInput, setPrimaryTimeInput] = useState(applicant.scheduledTime || "");
  const [fallbackTimeInput, setFallbackTimeInput] = useState(applicant.fallbackTime || "");

  const embedUrl = useMemo(() => getDriveEmbedUrl(applicant.resumeUrl), [applicant.resumeUrl]);
  
  const handleSaveTimes = async () => {
    if (onUpdateScheduledTimes) {
      await onUpdateScheduledTimes(applicant.id, primaryTimeInput || null, fallbackTimeInput || null);
      setIsEditingTimes(false);
    }
  };

  const handleAddCommentSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!commentText.trim()) return;
    onAddComment(applicant.id, commentText, currentUser.name);
    setCommentText("");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 bg-slate-950/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-[96vw] h-[96vh] flex flex-col rounded-3xl border border-slate-200/80 bg-slate-50 shadow-2xl dark:border-slate-800 dark:bg-slate-900 overflow-hidden animate-in zoom-in-95 duration-200">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-200/80 bg-white px-6 py-2.5 shrink-0 dark:border-slate-800 dark:bg-slate-950">
          <div>
            <div className="flex items-center gap-2">
              <span className="rounded-lg bg-indigo-500/10 p-1.5 text-indigo-650 dark:text-indigo-400">
                <User className="h-5 w-5" />
              </span>
              <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">
                Candidate Profile View
              </h2>
            </div>
            <div className="flex flex-wrap items-center gap-2 mt-0.5">
              <span className="text-xs text-slate-500 font-medium">
                <span className="font-semibold text-slate-800 dark:text-slate-200">{applicant.name}</span> &bull; ID: <span className="font-mono">{applicant.hashId}</span>
              </span>
              <span className="rounded-full bg-slate-100 dark:bg-slate-800 px-2.5 py-0.5 text-xs font-semibold text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
                Track: {applicant.cohort}
              </span>
              {applicant.studentId && (
                <span className="rounded-full bg-slate-100 dark:bg-slate-800 px-2.5 py-0.5 text-xs font-bold text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 font-mono">
                  UID: {applicant.studentId}
                </span>
              )}
              {applicant.year && (
                <span className="rounded-full bg-indigo-50 dark:bg-indigo-950/40 px-2.5 py-0.5 text-xs font-bold text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800/40 flex items-center gap-1">
                  🎓 Year: {applicant.year}
                </span>
              )}
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {currentUser.role === "ADMIN" && applicant.status === "rejected" && onUndoRejection && (
              <button
                type="button"
                onClick={() => onUndoRejection(applicant.id)}
                className="flex items-center gap-1.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold px-3.5 py-1.5 rounded-xl transition-all shadow-sm cursor-pointer mr-2"
              >
                <RotateCw className="h-4 w-4" />
                Undo Rejection
              </button>
            )}

            {currentUser.role === "ADMIN" && applicant.status === "interview" && onRescindInterview && (
              <button
                type="button"
                onClick={() => onRescindInterview(applicant.id)}
                className="flex items-center gap-1.5 bg-amber-50 hover:bg-amber-100 border border-amber-200 text-amber-800 text-xs font-bold px-3.5 py-1.5 rounded-xl transition-all shadow-sm cursor-pointer mr-2"
                title="Rescind interview offer and return candidate to graded list"
              >
                <RotateCw className="h-4 w-4" />
                Rescind Interview Offer
              </button>
            )}

            {currentUser.role === "ADMIN" && !["interview", "offered", "rejected"].includes(applicant.status) && (
              <div className="flex items-center gap-2 mr-2">
                {onSendInterview && applicant.status !== "interview" && (
                  <button
                    type="button"
                    onClick={() => onSendInterview(applicant.id)}
                    className="flex items-center gap-1.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-all shadow-sm cursor-pointer"
                  >
                    <Calendar className="h-4 w-4" />
                    Send to Interview
                  </button>
                )}
                {onSendOffer && (
                  <button
                    type="button"
                    onClick={() => onSendOffer(applicant.id)}
                    className="flex items-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-all shadow-sm cursor-pointer"
                  >
                    Send Offer
                  </button>
                )}
                {onSendReject && (
                  <button
                    type="button"
                    onClick={() => onSendReject(applicant.id)}
                    className="flex items-center gap-1.5 bg-slate-100 hover:bg-rose-50 text-rose-600 text-xs font-bold px-3 py-1.5 rounded-xl transition-all cursor-pointer"
                  >
                    Reject
                  </button>
                )}
              </div>
            )}
            
            <button
              onClick={onClose}
              className="rounded-xl border border-slate-150 p-2 text-slate-400 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900 hover:text-slate-655 cursor-pointer"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Modal Body - Side-by-Side Split */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          
          {/* Left Side: Resume Reader & Essay Box (70% width) */}
          <div className="w-full md:w-[70%] bg-slate-100 dark:bg-slate-950 flex flex-col overflow-hidden border-b md:border-b-0 md:border-r border-slate-200/80 dark:border-slate-800">
            
            {/* Resume Reader (100% height when showEssay is false) */}
            <div className={`${showEssay ? "h-[72%]" : "h-full"} flex flex-col overflow-hidden border-b border-slate-200 dark:border-slate-800 transition-all duration-300`}>
              <div className="h-11 border-b border-slate-200/80 bg-slate-50 dark:border-slate-800 dark:bg-slate-900 px-4 flex items-center justify-between shrink-0">
                <span className="text-xs font-semibold text-slate-550 dark:text-slate-400 flex items-center gap-1.5">
                  <FileText className="h-3.5 w-3.5" />
                  Applicant Resume ({zoom}%)
                </span>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setShowEssay(!showEssay)}
                    className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                      showEssay 
                        ? "bg-indigo-100 text-indigo-700 border border-indigo-300 dark:bg-indigo-950 dark:text-indigo-300 dark:border-indigo-800"
                        : "bg-slate-200 text-slate-700 hover:bg-slate-300 dark:bg-slate-800 dark:text-slate-300"
                    }`}
                  >
                    <BookOpen className="h-3.5 w-3.5" />
                    {showEssay ? "Hide Essay" : "Show Essay Split"}
                  </button>

                  {applicant.resumeUrl && (
                    <a
                      href={applicant.resumeUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1 bg-indigo-600 hover:bg-indigo-700 text-white text-[11px] font-bold px-2.5 py-1 rounded-lg transition-all shadow-sm"
                    >
                      Open Link ↗
                    </a>
                  )}
                  <button
                    onClick={() => setZoom(Math.max(50, zoom - 10))}
                    className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-550 cursor-pointer"
                    title="Zoom Out"
                  >
                    <ZoomOut className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => setZoom(Math.min(150, zoom + 10))}
                    className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-550 cursor-pointer"
                    title="Zoom In"
                  >
                    <ZoomIn className="h-4 w-4" />
                  </button>
                  <div className="h-4 w-px bg-slate-300 dark:bg-slate-700 mx-1" />
                  <button
                    onClick={() => setZoom(100)}
                    className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-550 cursor-pointer"
                    title="Reset Zoom"
                  >
                    <RotateCw className="h-4 w-4" />
                  </button>
                </div>
              </div>

              <div className="flex-1 overflow-hidden p-1 flex justify-center items-stretch bg-slate-100 dark:bg-slate-950">
                {embedUrl ? (
                  <div
                    className="w-full h-full bg-white rounded-xl border border-slate-200 dark:border-slate-800 shadow-md overflow-hidden transition-all origin-top duration-200 relative"
                    style={{ transform: `scale(${zoom / 100})` }}
                  >
                    <iframe
                      src={embedUrl}
                      className="w-full h-full border-0"
                      width="100%"
                      height="100%"
                      allow="autoplay; fullscreen"
                      title={`${applicant.name} Resume Viewer`}
                    />
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full w-full p-8 text-center bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm">
                    <FileText className="h-12 w-12 text-slate-300 dark:text-slate-700 mb-4" />
                    <p className="text-sm font-semibold text-slate-600 dark:text-slate-400">
                      No resume URL found in database for this applicant.
                    </p>
                  </div>
                )}
              </div>
            </div>

            {/* Optional Collapsible Essay Box */}
            {showEssay && (
              <div className="h-[28%] flex flex-col overflow-hidden bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 animate-in slide-in-from-bottom-5 duration-200">
              <div className="h-11 border-b border-slate-200/80 bg-slate-50 dark:border-slate-800 dark:bg-slate-900 px-4 flex items-center justify-between shrink-0">
                <span className="text-xs font-semibold text-slate-550 dark:text-slate-400 flex items-center gap-1.5">
                  <BookOpen className="h-3.5 w-3.5 text-indigo-500" />
                  Essay Response
                </span>
                <span className="text-[10px] bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-bold px-2 py-0.5 rounded-full">
                  Personal Statement
                </span>
              </div>
              <div className="flex-1 overflow-y-auto p-6 bg-slate-50/50 dark:bg-slate-950/20 shadow-inner">
                {applicant.shortAnswer ? (
                  <div className="prose prose-sm prose-slate dark:prose-invert max-w-none">
                    <h3 className="text-sm font-bold text-slate-800 dark:text-slate-100 mb-1">
                      Application Question: Tell me about yourself.
                    </h3>
                    <p className="text-[10px] text-slate-400 dark:text-slate-500 italic mt-0 mb-3">
                      Word Count: {applicant.shortAnswer.split(/\s+/).filter(Boolean).length} words
                    </p>
                    <div className="rounded-xl border border-slate-200/60 dark:border-slate-800 bg-white/70 dark:bg-slate-950/40 p-4 text-xs leading-relaxed text-slate-700 dark:text-slate-300 italic shadow-sm whitespace-pre-wrap">
                      "{applicant.shortAnswer}"
                    </div>
                  </div>
                ) : (
                  <div className="text-xs text-slate-500 italic p-4">
                    No application essay response recorded for this candidate.
                  </div>
                )}
              </div>
            </div>
            )}

          </div>

          {/* Right Side: Scorecard & Activity Timeline (30% width) */}
          <div className="w-full md:w-[30%] bg-white dark:bg-slate-900 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              
              {/* Scorecard Overview */}
              <div className="rounded-2xl border border-slate-200/80 bg-slate-50/40 p-5 space-y-4 dark:border-slate-800 dark:bg-slate-950/20">
                <div className="flex justify-between items-center border-b border-slate-200/80 pb-2">
                  <span className="text-xs font-bold text-slate-800 uppercase tracking-wider">Evaluation Scorecard</span>
                  <div className="flex items-center gap-1.5">
                    <span className="text-lg font-black text-indigo-650">
                      {applicant.score !== undefined ? applicant.score.toFixed(1) : "--"}
                    </span>
                    <span className="text-xs text-slate-500">/25.0</span>
                  </div>
                </div>

                {applicant.grades ? (
                  <div className="grid grid-cols-4 gap-2 text-center text-xs">
                    <div className="bg-white p-2 rounded-xl border border-slate-200/60 shadow-sm">
                      <span className="text-[10px] text-slate-400 font-bold uppercase block">Lead</span>
                      <span className="font-black text-slate-800">{applicant.grades.leadership}/5.0</span>
                    </div>
                    <div className="bg-white p-2 rounded-xl border border-slate-200/60 shadow-sm">
                      <span className="text-[10px] text-slate-400 font-bold uppercase block">Solve</span>
                      <span className="font-black text-slate-800">{applicant.grades.problemSolving}/5.0</span>
                    </div>
                    <div className="bg-white p-2 rounded-xl border border-slate-200/60 shadow-sm">
                      <span className="text-[10px] text-slate-400 font-bold uppercase block">Comm</span>
                      <span className="font-black text-slate-800">{applicant.grades.communication}/5.0</span>
                    </div>
                    <div className="bg-white p-2 rounded-xl border border-slate-200/60 shadow-sm">
                      <span className="text-[10px] text-slate-400 font-bold uppercase block">Essay</span>
                      <span className="font-black text-slate-800">
                        {applicant.grades.essay !== undefined ? `${applicant.grades.essay}/10` : "--"}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-xs text-slate-450 italic text-center">Unrated</p>
                )}
              </div>

              {/* Status & Grader Metadata */}
              <div className="grid grid-cols-2 gap-4 text-xs">
                <div className="rounded-xl border border-slate-100 p-3 bg-slate-50/50 dark:border-slate-800 dark:bg-slate-950/20">
                  <span className="text-slate-400 block font-bold uppercase text-[9px] tracking-wider">Status</span>
                  <span className="font-black text-slate-700 dark:text-slate-300 capitalize">{applicant.status.replace("_", " ")}</span>
                </div>
                <div className="rounded-xl border border-slate-100 p-3 bg-slate-50/50 dark:border-slate-800 dark:bg-slate-950/20">
                  <span className="text-slate-400 block font-bold uppercase text-[9px] tracking-wider">Assigned Grader</span>
                  <span className="font-black text-slate-700 dark:text-slate-300">{applicant.assignedGraderName || "Not Assigned"}</span>
                </div>
              </div>

              {/* Scheduled & Fallback Interview Timing Block */}
              <div className="rounded-2xl border border-indigo-100 p-4 bg-indigo-50/40 space-y-3 dark:border-slate-800 dark:bg-indigo-950/10">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-indigo-600" />
                    <span className="font-black text-slate-800 dark:text-slate-200 text-xs uppercase tracking-wider">
                      Interview Timing Slots
                    </span>
                  </div>
                  {currentUser.role === "ADMIN" && onUpdateScheduledTimes && (
                    <button
                      type="button"
                      onClick={() => {
                        if (isEditingTimes) {
                          handleSaveTimes();
                        } else {
                          setIsEditingTimes(true);
                        }
                      }}
                      className="text-[10px] font-bold text-indigo-700 hover:text-indigo-900 bg-indigo-100/80 px-2.5 py-1 rounded-lg transition-colors cursor-pointer"
                    >
                      {isEditingTimes ? "Save Slots" : "Edit Slots"}
                    </button>
                  )}
                </div>

                {!isEditingTimes ? (
                  <div className="grid grid-cols-2 gap-3 text-xs">
                    <div className="bg-white p-2.5 rounded-xl border border-indigo-100/80 shadow-xs">
                      <span className="text-[10px] font-bold text-indigo-600 block uppercase">Primary Time Slot</span>
                      <span className="font-bold text-slate-800">
                        {applicant.scheduledTime ? applicant.scheduledTime : "Not Assigned"}
                      </span>
                    </div>
                    <div className="bg-white p-2.5 rounded-xl border border-amber-200/80 shadow-xs">
                      <span className="text-[10px] font-bold text-amber-600 block uppercase">Fallback Time Slot</span>
                      <span className="font-bold text-slate-800">
                        {applicant.fallbackTime ? applicant.fallbackTime : "Not Assigned"}
                      </span>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-2 text-xs">
                    <div>
                      <label className="text-[10px] font-bold text-slate-600 uppercase block mb-1">Primary Interview Time</label>
                      <input
                        type="text"
                        value={primaryTimeInput}
                        onChange={(e) => setPrimaryTimeInput(e.target.value)}
                        placeholder="e.g. 09:00 AM or Sat 2:00 PM"
                        className="w-full bg-white border border-slate-200 rounded-lg px-3 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-indigo-500"
                      />
                    </div>
                    <div>
                      <label className="text-[10px] font-bold text-slate-600 uppercase block mb-1">Fallback Interview Time</label>
                      <input
                        type="text"
                        value={fallbackTimeInput}
                        onChange={(e) => setFallbackTimeInput(e.target.value)}
                        placeholder="e.g. 10:30 AM or Sun 3:30 PM"
                        className="w-full bg-white border border-slate-200 rounded-lg px-3 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-indigo-500"
                      />
                    </div>
                    <div className="flex justify-end gap-2 pt-1">
                      <button
                        type="button"
                        onClick={() => setIsEditingTimes(false)}
                        className="px-2.5 py-1 text-[10px] font-bold text-slate-500 hover:text-slate-700"
                      >
                        Cancel
                      </button>
                      <button
                        type="button"
                        onClick={handleSaveTimes}
                        className="px-3 py-1 text-[10px] font-bold bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 cursor-pointer"
                      >
                        Save Slots
                      </button>
                    </div>
                  </div>
                )}
              </div>

              {/* Google Form Responses Record */}
              {applicant.formResponses && (
                <div className="rounded-2xl border border-emerald-200 p-4 bg-emerald-50/40 space-y-2 dark:border-emerald-950 dark:bg-emerald-950/20">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-xs text-emerald-800 dark:text-emerald-300 uppercase tracking-wider flex items-center gap-1.5">
                      <FileText className="h-3.5 w-3.5 text-emerald-600" />
                      Saved Google Form Submission
                    </span>
                    {applicant.formResponses.submittedAt && (
                      <span className="text-[10px] text-emerald-600 font-mono">
                        {new Date(applicant.formResponses.submittedAt).toLocaleDateString()}
                      </span>
                    )}
                  </div>
                  <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-emerald-100 dark:border-emerald-900 text-xs space-y-1 font-mono text-slate-700 dark:text-slate-300">
                    <p><span className="font-bold text-slate-500">Primary Slot:</span> {applicant.formResponses.primarySlot || "N/A"}</p>
                    <p><span className="font-bold text-slate-500">Fallback Slot:</span> {applicant.formResponses.fallbackSlot || "N/A"}</p>
                  </div>
                </div>
              )}

              {/* Timeline Section */}
              <div className="space-y-3">
                <span className="text-xs font-bold text-slate-800 uppercase tracking-wider block">Evaluation Comments Timeline</span>
                <div className="space-y-3.5 max-h-[220px] overflow-y-auto pr-1">
                  {applicant.interviewComments && applicant.interviewComments.length > 0 ? (
                    applicant.interviewComments.map((comment) => (
                      <div key={comment.id} className="p-3.5 rounded-2xl bg-slate-50 border border-slate-100/80 shadow-sm relative dark:border-slate-800 dark:bg-slate-950/30">
                        <div className="flex justify-between items-center text-[10px] text-slate-450 border-b border-slate-100 pb-1.5 mb-2 dark:border-slate-800/80">
                          <span className="font-black text-slate-655 dark:text-slate-400">{comment.author}</span>
                          <span>{comment.timestamp}</span>
                        </div>
                        <p className="text-xs leading-relaxed text-slate-655 dark:text-slate-350">{comment.text}</p>
                      </div>
                    ))
                  ) : (
                    <div className="text-center py-6 border border-dashed border-slate-200 rounded-2xl">
                      <p className="text-xs text-slate-450 italic">No interview comments logged yet.</p>
                    </div>
                  )}
                </div>
              </div>

            </div>

            {/* Sticky Comment Editor Footer */}
            <div className="border-t border-slate-200/80 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/60">
              <form onSubmit={handleAddCommentSubmit} className="space-y-2">
                <div className="flex items-center gap-1.5 text-[10px] text-slate-500 px-1">
                  <span className="font-bold text-slate-700">Writing as:</span>
                  <span className="bg-indigo-50 text-indigo-650 px-2 py-0.5 rounded font-black">
                    {currentUser.name} ({currentUser.role})
                  </span>
                </div>
                
                <div className="flex gap-2">
                  <textarea
                    placeholder="Input future interview comments, notes, or reviews..."
                    value={commentText}
                    onChange={(e) => setCommentText(e.target.value)}
                    rows={2}
                    className="flex-1 rounded-xl border border-slate-200 bg-white p-2.5 text-xs text-slate-700 outline-none focus:border-indigo-500 resize-none shadow-sm transition-all"
                    required
                  />
                  <button
                    type="submit"
                    className="h-12 w-12 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white flex items-center justify-center shadow-sm cursor-pointer shrink-0 transition-colors"
                  >
                    <Send className="h-4 w-4" />
                  </button>
                </div>
              </form>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}
