import React, { useState } from "react";
import {
  X,
  FileText,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Download,
  AlertCircle,
  BookOpen,
  Briefcase,
  Layers,
} from "lucide-react";
import { Applicant } from "./ApplicantCard";

interface GradingModalProps {
  applicant: Applicant;
  onClose: () => void;
  onSubmitGrade: (
    applicantId: string,
    grades: { leadership: number; problemSolving: number; communication: number; essay: number },
    notes: string
  ) => void;
}

function getDriveEmbedUrl(url?: string): string | null {
  if (!url) return null;
  const trimmed = url.trim();
  if (!trimmed || trimmed === "https://drive.google.com" || trimmed === "https://drive.google.com/") {
    return null;
  }

  // Handle the "open?id=..." format generated by Google Forms / Apps Script
  if (trimmed.includes("open?id=")) {
    const fileId = trimmed.split("open?id=")[1].split("&")[0];
    return `https://drive.google.com/file/d/${fileId}/preview`;
  }

  // Handle standard Google Drive view links (/file/d/ID/...)
  if (trimmed.includes("/file/d/")) {
    const fileId = trimmed.split("/file/d/")[1].split("/")[0];
    return `https://drive.google.com/file/d/${fileId}/preview`;
  }

  return trimmed;
}

export default function GradingModal({
  applicant,
  onClose,
  onSubmitGrade,
}: GradingModalProps) {
  const [leadership, setLeadership] = useState(
    applicant.grades?.leadership || 3.0
  );
  const [problemSolving, setProblemSolving] = useState(
    applicant.grades?.problemSolving || 3.0
  );
  const [communication, setCommunication] = useState(
    applicant.grades?.communication || 3.0
  );
  const [essayScore, setEssayScore] = useState(
    applicant.grades?.essay || 5
  );
  const [notes, setNotes] = useState("");
  const [zoom, setZoom] = useState(100);
  const [showEssay, setShowEssay] = useState(false);

  const embedUrl = getDriveEmbedUrl(applicant.resumeUrl);

  // Calculate overall score (sum of the core rubric + essay score, max 25)
  const totalScore = leadership + problemSolving + communication + essayScore;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("GradingModal submitting grades:", {
      leadership,
      problemSolving,
      communication,
      essay: essayScore,
    }, "notes:", notes);
    onSubmitGrade(
      applicant.id,
      {
        leadership,
        problemSolving,
        communication,
        essay: essayScore,
      },
      notes
    );
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 bg-slate-950/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-7xl h-[95vh] flex flex-col rounded-3xl border border-slate-200/80 bg-slate-55 shadow-2xl dark:border-slate-800 dark:bg-slate-900 overflow-hidden animate-in zoom-in-95 duration-200">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-200/80 bg-white px-6 py-3 shrink-0 dark:border-slate-800 dark:bg-slate-950">
          <div>
            <div className="flex items-center gap-2">
              <span className="rounded-lg bg-blue-500/10 p-1.5 text-blue-600 dark:text-blue-400">
                <FileText className="h-5 w-5" />
              </span>
              <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">
                Rubric Evaluation & Resume
              </h2>
            </div>
            <p className="text-xs text-slate-400 dark:text-slate-500 mt-0.5">
              Applicant: <span className="font-semibold text-slate-600 dark:text-slate-400">{applicant.name}</span> &bull; ID: <span className="font-mono">{applicant.hashId}</span>
            </p>
          </div>
          
          <button
            onClick={onClose}
            className="rounded-xl border border-slate-100 p-2 text-slate-400 hover:bg-slate-55 dark:border-slate-800 dark:hover:bg-slate-900 hover:text-slate-600 dark:hover:text-slate-300 cursor-pointer"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Modal Body - Side-by-Side Split */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          
          {/* Left Side: Mock PDF Resume Reader & Essay Box (70% width) */}
          <div className="w-full md:w-[70%] bg-slate-100 dark:bg-slate-950 flex flex-col overflow-hidden border-b md:border-b-0 md:border-r border-slate-200/80 dark:border-slate-800">
            
            {/* Resume Reader (100% height when showEssay is false) */}
            <div className={`${showEssay ? "h-[72%]" : "h-full"} flex flex-col overflow-hidden border-b border-slate-200 dark:border-slate-800 transition-all duration-300`}>
              {/* Resume PDF Toolbar */}
              <div className="h-11 border-b border-slate-200/80 bg-slate-50 dark:border-slate-800 dark:bg-slate-900 px-4 flex items-center justify-between shrink-0">
                <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
                  <FileText className="h-3.5 w-3.5" />
                  Applicant Resume ({zoom}%)
                </span>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setShowEssay(!showEssay)}
                    className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-bold transition-all ${
                      showEssay 
                        ? "bg-indigo-100 text-indigo-700 border border-indigo-300 dark:bg-indigo-950 dark:text-indigo-300 dark:border-indigo-800"
                        : "bg-slate-200 text-slate-700 hover:bg-slate-300 dark:bg-slate-800 dark:text-slate-300"
                    }`}
                  >
                    <BookOpen className="h-3.5 w-3.5" />
                    {showEssay ? "Hide Essay" : "Show Essay Split"}
                  </button>

                  {applicant.resumeUrl && (
                    <a
                      href={applicant.resumeUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1 bg-indigo-600 hover:bg-indigo-700 text-white text-[11px] font-bold px-2.5 py-1 rounded-lg transition-all shadow-sm"
                    >
                      Open Link ↗
                    </a>
                  )}
                  <button
                    type="button"
                    onClick={() => setZoom(Math.max(50, zoom - 10))}
                    className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-550 cursor-pointer"
                    title="Zoom Out"
                  >
                    <ZoomOut className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => setZoom(Math.min(150, zoom + 10))}
                    className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-550 cursor-pointer"
                    title="Zoom In"
                  >
                    <ZoomIn className="h-4 w-4" />
                  </button>
                  <div className="h-4 w-px bg-slate-300 dark:bg-slate-700 mx-1" />
                  <button
                    type="button"
                    onClick={() => setZoom(100)}
                    className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-550 cursor-pointer"
                    title="Reset Zoom"
                  >
                    <RotateCw className="h-4 w-4" />
                  </button>
                </div>
              </div>

              {/* Resume Viewer Canvas */}
              <div className="flex-1 overflow-hidden p-1 flex justify-center items-stretch bg-slate-100 dark:bg-slate-950">
                {embedUrl ? (
                  <div
                    className="w-full h-full bg-white rounded-xl border border-slate-200 dark:border-slate-800 shadow-md overflow-hidden transition-all origin-top duration-200 relative"
                    style={{ transform: `scale(${zoom / 100})` }}
                  >
                    <iframe
                      src={embedUrl}
                      className="w-full h-full border-0"
                      width="100%"
                      height="100%"
                      allow="autoplay; fullscreen"
                      title={`${applicant.name} Resume Viewer`}
                    />
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full w-full p-8 text-center bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm">
                    <FileText className="h-12 w-12 text-slate-300 dark:text-slate-700 mb-4" />
                    <p className="text-sm font-semibold text-slate-600 dark:text-slate-400">
                      No resume URL found in database for this applicant.
                    </p>
                  </div>
                )}
              </div>
            </div>

            {/* Optional Collapsible Essay Box */}
            {showEssay && (
              <div className="h-[28%] flex flex-col overflow-hidden bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 animate-in slide-in-from-bottom-5 duration-200">
                {/* Essay Toolbar */}
                <div className="h-11 border-b border-slate-200/80 bg-slate-50 dark:border-slate-800 dark:bg-slate-900 px-4 flex items-center justify-between shrink-0">
                  <span className="text-xs font-semibold text-slate-550 dark:text-slate-400 flex items-center gap-1.5">
                    <BookOpen className="h-3.5 w-3.5 text-indigo-500" />
                    Essay Response
                  </span>
                  <span className="text-[10px] bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-bold px-2 py-0.5 rounded-full">
                    Case Study Challenge
                  </span>
                </div>
                {/* Essay Content Area */}
                <div className="flex-1 overflow-y-auto p-6 bg-slate-55/50 dark:bg-slate-950/20 shadow-inner">
                  {applicant.shortAnswer ? (
                    <div className="prose prose-sm prose-slate dark:prose-invert max-w-none">
                      <h3 className="text-sm font-bold text-slate-800 dark:text-slate-100 mb-1">
                        Application Question: Tell me about yourself.
                      </h3>
                      <p className="text-[10px] text-slate-400 dark:text-slate-500 italic mt-0 mb-3">
                        Word Count: {applicant.shortAnswer.split(/\s+/).filter(Boolean).length} words
                      </p>
                      <div className="rounded-xl border border-slate-200/60 dark:border-slate-800 bg-white/70 dark:bg-slate-950/40 p-4 text-xs leading-relaxed text-slate-700 dark:text-slate-300 italic shadow-sm whitespace-pre-wrap">
                        "{applicant.shortAnswer}"
                      </div>
                    </div>
                  ) : (
                    <div className="text-xs text-slate-500 italic p-4">
                      No application essay response recorded for this candidate.
                    </div>
                  )}
                </div>
              </div>
            )}

          </div>

          {/* Right Side: Rubric Form (40% width) */}
          <div className="w-full md:w-2/5 bg-white dark:bg-slate-900 flex flex-col overflow-hidden">
            <form onSubmit={handleSubmit} className="flex-1 flex flex-col justify-between overflow-y-auto">
              
              {/* Form Content */}
              <div className="p-6 space-y-6">
                
                {/* Rubric Card Alert */}
                <div className="rounded-2xl bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-100 dark:border-indigo-950 p-4">
                  <div className="flex gap-3">
                    <AlertCircle className="h-5 w-5 text-indigo-600 dark:text-indigo-400 shrink-0" />
                    <div>
                      <h4 className="text-sm font-bold text-indigo-950 dark:text-indigo-200">
                        Grading Standards
                      </h4>
                      <p className="text-xs text-indigo-700 dark:text-indigo-300 mt-0.5 leading-relaxed">
                        Score each core criteria from 1.0 to 5.0 and the essay evaluation from 1 to 10. Total score sums up to a maximum of 25.0. Be objective and leave thorough notes.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Score Summary Display */}
                <div className="rounded-2xl border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 p-4 text-center">
                  <div className="text-4xl font-black text-slate-800 dark:text-white">
                    {totalScore.toFixed(1)}
                    <span className="text-lg text-slate-400 dark:text-slate-500 font-normal">
                      /25.0
                    </span>
                  </div>
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500 mt-1 block">
                    Calculated Score
                  </span>
                </div>

                {/* Leadership Score */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <label className="text-sm font-bold text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
                      Leadership
                    </label>
                    <span className="text-sm font-black bg-indigo-50 text-indigo-600 px-2 py-0.5 rounded-lg dark:bg-indigo-500/10 dark:text-indigo-400">
                      {leadership.toFixed(1)} / 5.0
                    </span>
                  </div>
                  <input
                    type="range"
                    min="1"
                    max="5"
                    step="0.5"
                    value={leadership}
                    onChange={(e) => setLeadership(parseFloat(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600 dark:bg-slate-800"
                  />
                  <div className="flex justify-between text-[10px] text-slate-400 dark:text-slate-500 font-medium">
                    <span>1.0 - Minimal initiative</span>
                    <span>3.0 - Solid manager</span>
                    <span>5.0 - Visionary leader</span>
                  </div>
                </div>

                {/* Problem Solving Score */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <label className="text-sm font-bold text-slate-800 dark:text-slate-200">
                      Problem Solving
                    </label>
                    <span className="text-sm font-black bg-amber-50 text-amber-600 px-2 py-0.5 rounded-lg dark:bg-amber-500/10 dark:text-amber-400">
                      {problemSolving.toFixed(1)} / 5.0
                    </span>
                  </div>
                  <input
                    type="range"
                    min="1"
                    max="5"
                    step="0.5"
                    value={problemSolving}
                    onChange={(e) => setProblemSolving(parseFloat(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-amber-600 dark:bg-slate-800"
                  />
                  <div className="flex justify-between text-[10px] text-slate-400 dark:text-slate-500 font-medium">
                    <span>1.0 - Lacks structure</span>
                    <span>3.0 - Framework applied</span>
                    <span>5.0 - Flawless synthesis</span>
                  </div>
                </div>

                {/* Communication Score */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <label className="text-sm font-bold text-slate-800 dark:text-slate-200">
                      Communication
                    </label>
                    <span className="text-sm font-black bg-teal-50 text-teal-600 px-2 py-0.5 rounded-lg dark:bg-teal-500/10 dark:text-teal-400">
                      {communication.toFixed(1)} / 5.0
                    </span>
                  </div>
                  <input
                    type="range"
                    min="1"
                    max="5"
                    step="0.5"
                    value={communication}
                    onChange={(e) => setCommunication(parseFloat(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-teal-600 dark:bg-slate-800"
                  />
                  <div className="flex justify-between text-[10px] text-slate-400 dark:text-slate-500 font-medium">
                    <span>1.0 - Hard to follow</span>
                    <span>3.0 - Structured, clear</span>
                    <span>5.0 - Extremely persuasive</span>
                  </div>
                </div>

                {/* Essay Evaluation Score Slider */}
                <div className="space-y-2 pt-4 border-t border-slate-150 dark:border-slate-800">
                  <div className="flex justify-between items-center">
                    <label className="text-sm font-bold text-slate-800 dark:text-slate-200">
                      Essay Evaluation
                    </label>
                    <span className="text-sm font-black bg-blue-50 text-blue-600 px-2 py-0.5 rounded-lg dark:bg-blue-500/10 dark:text-blue-400">
                      {essayScore} / 10
                    </span>
                  </div>
                  <input
                    type="range"
                    min="1"
                    max="10"
                    step="1"
                    value={essayScore}
                    onChange={(e) => setEssayScore(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600 dark:bg-slate-800"
                  />
                  <div className="flex justify-between text-[10px] text-slate-400 dark:text-slate-500 font-medium">
                    <span>1 - Weak logic</span>
                    <span>5 - Capable analysis</span>
                    <span>10 - C-Suite ready</span>
                  </div>
                </div>

                {/* Notes Textarea */}
                <div className="space-y-2">
                  <label className="text-sm font-bold text-slate-800 dark:text-slate-200">
                    Evaluation Notes
                  </label>
                  <textarea
                    placeholder="Provide specific notes regarding resumes, strengths, weaknesses, and performance markers..."
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    rows={4}
                    className="w-full rounded-2xl border border-slate-200/80 bg-white p-3 text-xs text-slate-700 outline-none focus:border-indigo-500 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 focus:ring-1 focus:ring-indigo-500 transition-all resize-none"
                    required
                  />
                </div>
              </div>

              {/* Form Action Footer */}
              <div className="border-t border-slate-200/80 bg-slate-50 p-6 dark:border-slate-800 dark:bg-slate-950/60 flex items-center justify-between gap-3">
                <button
                  type="button"
                  onClick={onClose}
                  className="flex-1 h-10 border border-slate-200 rounded-xl bg-white text-xs font-bold text-slate-700 hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 dark:hover:bg-slate-900 transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex-1 h-10 rounded-xl bg-blue-600 text-xs font-bold text-white hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 transition-colors shadow-sm cursor-pointer"
                >
                  Submit Evaluation
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
