import React, { useState } from "react";
import {
  X,
  FileText,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Download,
  AlertCircle,
  BookOpen,
  Briefcase,
  Layers,
  GraduationCap,
  ExternalLink,
  CalendarCheck,
} from "lucide-react";
import { Applicant } from "./ApplicantCard";
import {
  RUBRICS,
  getApplicantRubricKey,
  RubricConfig,
  RubricKey,
  getRubricTotalPoints,
  getRubricCriteriaList,
  getCriterionPercentage,
  getNormalizedBenchmarks,
  BenchmarkItem,
} from "@/utils/rubrics";

interface GradingModalProps {
  applicant: Applicant;
  onClose: () => void;
  onSubmitGrade: (
    applicantId: string,
    grades: Record<string, number>,
    notes: string
  ) => void;
  customRubrics?: Record<RubricKey, RubricConfig>;
  currentUser?: { name: string; email: string; role: string; id?: string };
}

function getDriveEmbedUrl(url?: string): string | null {
  if (!url) return null;
  const trimmed = url.trim();
  if (!trimmed || trimmed === "https://drive.google.com" || trimmed === "https://drive.google.com/") {
    return null;
  }

  // Handle the "open?id=..." format generated by Google Forms / Apps Script
  if (trimmed.includes("open?id=")) {
    const fileId = trimmed.split("open?id=")[1].split("&")[0];
    return `https://drive.google.com/file/d/${fileId}/preview`;
  }

  // Handle standard Google Drive view links (/file/d/ID/...)
  if (trimmed.includes("/file/d/")) {
    const fileId = trimmed.split("/file/d/")[1].split("/")[0];
    return `https://drive.google.com/file/d/${fileId}/preview`;
  }

  return trimmed;
}

export default function GradingModal({
  applicant,
  onClose,
  onSubmitGrade,
  customRubrics,
  currentUser,
}: GradingModalProps) {
  const resolvedCustomRubrics = customRubrics || (() => {
    try {
      const saved = localStorage.getItem("bsn_custom_rubrics");
      if (saved) return JSON.parse(saved);
    } catch (_) {}
    return null;
  })();

  const rKey = getApplicantRubricKey(applicant);
  const activeRubric = resolvedCustomRubrics
    ? (resolvedCustomRubrics[rKey] || RUBRICS[rKey])
    : RUBRICS[rKey];

  const criteriaList = getRubricCriteriaList(activeRubric, rKey);

  // Find the current reviewer's assignment info if they already submitted or have notes
  const myAssignment = (applicant.assignedGraders || []).find(
    (g) =>
      (currentUser?.id && g.graderId === currentUser.id) ||
      (currentUser?.name && g.graderName.toLowerCase() === currentUser.name.toLowerCase())
  );

  const [scores, setScores] = useState<Record<string, number>>(() => {
    const initial: Record<string, number> = {};
    const existingGrades =
      myAssignment?.grades ||
      (myAssignment?.score !== undefined ? undefined : applicant.grades);

    criteriaList.forEach((c) => {
      const existing = existingGrades ? (existingGrades as any)[c.id] : undefined;
      const bms = getNormalizedBenchmarks(c).sort((a, b) => a.point - b.point);
      if (existing !== undefined) {
        initial[c.id] = Number(existing);
      } else if (bms.length > 0) {
        const midIdx = Math.floor(bms.length / 2);
        initial[c.id] = bms[midIdx].point;
      } else {
        initial[c.id] = Math.round(c.maxScore / 2);
      }
    });
    return initial;
  });

  const [notes, setNotes] = useState<string>(() => {
    return myAssignment?.notes || "";
  });
  const [zoom, setZoom] = useState(100);
  const [showEssay, setShowEssay] = useState(false);
  const [activeBenchmarkTab, setActiveBenchmarkTab] = useState<Record<string, string>>({});

  const embedUrl = getDriveEmbedUrl(applicant.resumeUrl);

  const totalMaxPoints = getRubricTotalPoints(activeRubric);
  const totalEarnedPoints = Object.values(scores).reduce((acc, val) => acc + (Number(val) || 0), 0);
  const percentageEarned = totalMaxPoints ? ((totalEarnedPoints / totalMaxPoints) * 100).toFixed(1) : "0.0";

  const handleScoreChange = (criterionId: string, val: number) => {
    setScores((prev) => ({
      ...prev,
      [criterionId]: val,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("GradingModal submitting grades:", scores, "notes:", notes);
    onSubmitGrade(applicant.id, scores, notes);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 bg-slate-950/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-7xl h-[95vh] flex flex-col rounded-3xl border border-slate-200/80 bg-slate-55 shadow-2xl dark:border-slate-800 dark:bg-slate-900 overflow-hidden animate-in zoom-in-95 duration-200">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-200/80 bg-white px-6 py-3 shrink-0 dark:border-slate-800 dark:bg-slate-950">
          <div>
            <div className="flex items-center gap-2">
              <span className="rounded-lg bg-blue-500/10 p-1.5 text-blue-600 dark:text-blue-400">
                <FileText className="h-5 w-5" />
              </span>
              <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">
                Rubric Evaluation & Resume
              </h2>
            </div>
            <p className="text-xs text-slate-400 dark:text-slate-500 mt-0.5">
              Applicant: <span className="font-semibold text-slate-600 dark:text-slate-400">{applicant.name}</span> &bull; ID: <span className="font-mono">{applicant.hashId}</span>
            </p>
          </div>
          
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowEssay(!showEssay)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                showEssay
                  ? "bg-indigo-600 text-white border-indigo-600 shadow-sm"
                  : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700"
              }`}
            >
              <BookOpen className="h-3.5 w-3.5" />
              {showEssay ? "View Resume" : "View Short Answer Essay"}
            </button>

            <button
              onClick={onClose}
              className="rounded-xl border border-slate-200 p-2 text-slate-400 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900 hover:text-slate-600 cursor-pointer"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Modal Body - Split View */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          
          {/* Left Side: Resume Reader or Essay Viewer */}
          <div className="w-full md:w-3/5 bg-slate-100 dark:bg-slate-950 flex flex-col overflow-hidden border-b md:border-b-0 md:border-r border-slate-200/80 dark:border-slate-800">
            
            {!showEssay ? (
              <div className="h-full flex flex-col overflow-hidden">
                <div className="h-11 border-b border-slate-200/80 bg-slate-50 dark:border-slate-800 dark:bg-slate-900 px-4 flex items-center justify-between shrink-0">
                  <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
                    <Briefcase className="h-3.5 w-3.5" />
                    Applicant Resume
                  </span>
                  
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setZoom(Math.max(50, zoom - 10))}
                      className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400"
                      title="Zoom Out"
                    >
                      <ZoomOut className="h-3.5 w-3.5" />
                    </button>
                    <span className="text-[11px] font-mono text-slate-500 w-10 text-center">{zoom}%</span>
                    <button
                      onClick={() => setZoom(Math.min(150, zoom + 10))}
                      className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400"
                      title="Zoom In"
                    >
                      <ZoomIn className="h-3.5 w-3.5" />
                    </button>
                    {applicant.resumeUrl && (
                      <a
                        href={applicant.resumeUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="p-1 rounded hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400 ml-2"
                        title="Open in new tab"
                      >
                        <Download className="h-3.5 w-3.5" />
                      </a>
                    )}
                  </div>
                </div>

                <div className="flex-1 bg-slate-200/60 dark:bg-slate-950 p-4 overflow-auto flex justify-center items-start">
                  {embedUrl ? (
                    <div
                      style={{ transform: `scale(${zoom / 100})`, transformOrigin: "top center" }}
                      className="w-full h-full min-h-[600px] transition-transform duration-150"
                    >
                      <iframe
                        src={embedUrl}
                        className="w-full h-full rounded-xl shadow-lg border border-slate-300 dark:border-slate-800 bg-white"
                        title="Applicant Resume"
                      />
                    </div>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-full text-slate-400 space-y-3">
                      <FileText className="h-12 w-12 stroke-1" />
                      <p className="text-sm font-medium">No valid resume URL provided for preview.</p>
                      {applicant.resumeUrl && (
                        <a
                          href={applicant.resumeUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="text-xs text-indigo-600 underline font-bold"
                        >
                          Try opening raw link: {applicant.resumeUrl}
                        </a>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col p-6 overflow-y-auto space-y-4 bg-white dark:bg-slate-900">
                <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-3">
                  <BookOpen className="h-5 w-5 text-indigo-600" />
                  <div>
                    <h3 className="text-base font-bold text-slate-800 dark:text-slate-100">
                      Application Short Answer Essay
                    </h3>
                    <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">
                      "What is something you are genuinely passionate about, and what have you done to pursue that interest?"
                    </p>
                  </div>
                </div>
                <div className="p-5 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800 text-slate-700 dark:text-slate-300 text-sm leading-relaxed whitespace-pre-wrap">
                  {applicant.shortAnswer || applicant.formResponses?.short_answer || (
                    <div className="text-xs text-slate-400 italic">
                      No application essay response recorded for this candidate.
                    </div>
                  )}
                </div>

                {/* Additional Candidate Information: Major & LinkedIn */}
                {(() => {
                  const majorText =
                    applicant.major ||
                    applicant.formResponses?.major ||
                    applicant.formResponses?.["Major(s) and Minor(s)"];

                  const rawLinkedin =
                    applicant.linkedinUrl ||
                    applicant.formResponses?.linkedin_url ||
                    applicant.formResponses?.linkedin ||
                    applicant.formResponses?.["LinkedIn (optional)"];

                  const linkedinHref = rawLinkedin
                    ? rawLinkedin.startsWith("http")
                      ? rawLinkedin
                      : `https://${rawLinkedin}`
                    : null;

                  const attendanceCount =
                    typeof applicant.attendanceCount === "number"
                      ? applicant.attendanceCount
                      : typeof applicant.formResponses?.attendance_count === "number"
                      ? applicant.formResponses.attendance_count
                      : Array.isArray(applicant.formResponses?.attendance_events)
                      ? applicant.formResponses.attendance_events.length
                      : 0;

                  const attendanceEvents =
                    applicant.attendanceEvents ||
                    applicant.formResponses?.attendance_events ||
                    applicant.formResponses?.attendanceEvents ||
                    [];

                  return (
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
                      <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800 flex flex-col justify-center">
                        <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 flex items-center gap-1.5">
                          <GraduationCap className="h-3.5 w-3.5 text-indigo-500" />
                          Major(s) & Minor(s)
                        </span>
                        <p className="text-xs font-semibold text-slate-800 dark:text-slate-200 mt-1 truncate" title={majorText || undefined}>
                          {majorText || <span className="italic text-slate-400 font-normal">Not specified</span>}
                        </p>
                      </div>

                      <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800 flex flex-col justify-center">
                        <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 flex items-center gap-1.5">
                          <ExternalLink className="h-3.5 w-3.5 text-blue-500" />
                          LinkedIn Profile
                        </span>
                        <div className="mt-1">
                          {linkedinHref ? (
                            <a
                              href={linkedinHref}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="inline-flex items-center gap-1 text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline truncate max-w-full"
                              title={linkedinHref}
                            >
                              <span className="truncate">{rawLinkedin}</span>
                              <ExternalLink className="h-3 w-3 shrink-0" />
                            </a>
                          ) : (
                            <span className="text-xs italic text-slate-400 font-normal">Not provided</span>
                          )}
                        </div>
                      </div>

                      <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800 flex flex-col justify-center">
                        <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 flex items-center gap-1.5">
                          <CalendarCheck className="h-3.5 w-3.5 text-emerald-500" />
                          Events Attended
                        </span>
                        <div className="mt-1">
                          {attendanceCount > 0 ? (
                            <div className="flex flex-col gap-1">
                              <span className="inline-flex items-center gap-1.5">
                                <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-extrabold bg-emerald-100 text-emerald-800 dark:bg-emerald-950/80 dark:text-emerald-300 border border-emerald-200/80 dark:border-emerald-800/60 font-mono">
                                  {attendanceCount} {attendanceCount === 1 ? "Event" : "Events"}
                                </span>
                              </span>
                              {attendanceEvents.length > 0 && (
                                <div className="flex flex-wrap gap-1 mt-0.5 max-h-16 overflow-y-auto">
                                  {attendanceEvents.map((evt: any, idx: number) => (
                                    <span
                                      key={idx}
                                      className="text-[10px] font-medium bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-300 px-1.5 py-0.5 rounded border border-slate-200 dark:border-slate-800 truncate max-w-full"
                                      title={evt.questions ? `Question asked: "${evt.questions}"` : evt.formTitle || undefined}
                                    >
                                      {evt.eventName || evt.formTitle || "Event"}
                                    </span>
                                  ))}
                                </div>
                              )}
                            </div>
                          ) : (
                            <span className="text-xs italic text-slate-400 font-normal">0 events recorded</span>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })()}
              </div>
            )}

          </div>

          {/* Right Side: 9 Rubric Categories Form */}
          <div className="w-full md:w-2/5 bg-white dark:bg-slate-900 flex flex-col overflow-hidden">
            <form onSubmit={handleSubmit} className="flex-1 flex flex-col justify-between overflow-y-auto">
              
              {/* Form Content */}
              <div className="p-6 space-y-6">
                
                {/* Rubric Banner */}
                <div className="rounded-2xl bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-100 dark:border-indigo-950 p-4">
                  <div className="flex gap-3">
                    <AlertCircle className="h-5 w-5 text-indigo-600 dark:text-indigo-400 shrink-0" />
                    <div>
                      <h4 className="text-sm font-bold text-indigo-950 dark:text-indigo-200">
                        {activeRubric.title}
                      </h4>
                      <p className="text-xs text-indigo-700 dark:text-indigo-300 mt-0.5 leading-relaxed">
                        Evaluate across all 9 rubric categories. Points assigned per category build your total evaluation score out of <strong>{totalMaxPoints} Max Points</strong>.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Score Summary Display */}
                <div className="rounded-2xl border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 p-4 text-center">
                  <div className="text-4xl font-black text-slate-800 dark:text-white">
                    {totalEarnedPoints.toFixed(1)}
                    <span className="text-lg text-slate-400 dark:text-slate-500 font-normal">
                      /{totalMaxPoints}.0
                    </span>
                    <span className="text-base font-extrabold text-indigo-600 ml-2 font-mono">
                      ({percentageEarned}%)
                    </span>
                  </div>
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500 mt-1 block">
                    Calculated Evaluation Score
                  </span>
                </div>

                {/* Render 9 Rubric Categories */}
                <div className="space-y-6">
                  {criteriaList.map((criterion, idx) => {
                    const rawBenchmarks = getNormalizedBenchmarks(criterion);
                    const benchmarks = [...rawBenchmarks].sort((a, b) => a.point - b.point);
                    
                    const currentScore = scores[criterion.id] !== undefined
                      ? scores[criterion.id]
                      : (benchmarks.length > 0 ? benchmarks[Math.floor(benchmarks.length / 2)].point : Math.round(criterion.maxScore / 2));

                    let currentIdx = benchmarks.findIndex((b) => Math.abs(b.point - currentScore) < 0.05);
                    if (currentIdx === -1 && benchmarks.length > 0) {
                      let minDiff = Infinity;
                      benchmarks.forEach((b, bIdx) => {
                        const diff = Math.abs(b.point - currentScore);
                        if (diff < minDiff) {
                          minDiff = diff;
                          currentIdx = bIdx;
                        }
                      });
                    }
                    if (currentIdx === -1) currentIdx = 0;

                    const selectedBm = benchmarks[currentIdx] || benchmarks[0];
                    const weightPct = getCriterionPercentage(criterion, activeRubric);

                    return (
                      <div key={criterion.id} className="space-y-2 p-3.5 rounded-2xl border border-slate-150 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/40">
                        <div className="flex justify-between items-start">
                          <div>
                            <label className="text-xs font-extrabold text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
                              <span className="text-slate-400 font-mono text-[11px]">{idx + 1}.</span> {criterion.name}
                            </label>
                            <p className="text-[10px] text-slate-500 mt-0.5 leading-tight">{criterion.description}</p>
                          </div>
                          
                          <div className="flex items-center gap-1.5 shrink-0 ml-2">
                            <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-300 dark:border-slate-700" title="Calculated Category Weight Percentage (Read-only)">
                              {weightPct}
                            </span>
                            <span className="text-xs font-black bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded-lg dark:bg-indigo-500/10 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-900 font-mono">
                              {currentScore.toFixed(1)} / {criterion.maxScore}.0 pts
                            </span>
                          </div>
                        </div>

                        {/* Snapping Point Slider */}
                        {benchmarks.length > 0 ? (
                          <div className="space-y-1">
                            <input
                              type="range"
                              min={0}
                              max={benchmarks.length - 1}
                              step={1}
                              value={currentIdx}
                              onChange={(e) => {
                                const targetIdx = parseInt(e.target.value, 10);
                                const targetBm = benchmarks[targetIdx];
                                if (targetBm) {
                                  handleScoreChange(criterion.id, targetBm.point);
                                }
                              }}
                              className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600 dark:bg-slate-800"
                            />
                            <div className="flex justify-between text-[10px] font-mono font-bold text-slate-400 px-1">
                              {benchmarks.map((bm, bIdx) => (
                                <span
                                  key={bm.id || bIdx}
                                  onClick={() => handleScoreChange(criterion.id, bm.point)}
                                  className={`cursor-pointer hover:text-indigo-600 transition-colors ${
                                    currentIdx === bIdx ? "text-indigo-600 dark:text-indigo-400 font-extrabold" : ""
                                  }`}
                                >
                                  {bm.point.toFixed(1)} Pts
                                </span>
                              ))}
                            </div>
                          </div>
                        ) : (
                          <input
                            type="range"
                            min="0"
                            max={criterion.maxScore}
                            step="0.5"
                            value={currentScore}
                            onChange={(e) => handleScoreChange(criterion.id, parseFloat(e.target.value))}
                            className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600 dark:bg-slate-800"
                          />
                        )}

                        {/* Benchmark Guidance Points */}
                        <div className="pt-2 border-t border-slate-200/60 dark:border-slate-800/80 space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="text-[10px] font-bold uppercase text-slate-400">Benchmark Guidance Points:</span>
                          </div>
                          <div className="flex items-center gap-1.5 overflow-x-auto pb-1">
                            {benchmarks.map((bm, bIdx) => {
                              const isSelected = currentIdx === bIdx;
                              return (
                                <button
                                  key={bm.id || bIdx}
                                  type="button"
                                  onClick={() => handleScoreChange(criterion.id, bm.point)}
                                  className={`px-2.5 py-1 rounded-lg text-[11px] font-mono font-bold transition-all border shrink-0 cursor-pointer ${
                                    isSelected
                                      ? "bg-indigo-600 text-white border-indigo-600 shadow-xs"
                                      : "bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-800 hover:bg-slate-50"
                                  }`}
                                >
                                  {bm.point.toFixed(1)} Pts
                                </button>
                              );
                            })}
                          </div>
                          {selectedBm && (
                            <div className="p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 text-[11px] text-slate-700 dark:text-slate-300 leading-relaxed font-sans shadow-2xs">
                              <strong className="font-bold text-indigo-600 dark:text-indigo-400">{selectedBm.point.toFixed(1)} Points Guidance:</strong> {selectedBm.guidance}
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>

                {/* Notes Textarea */}
                <div className="space-y-2 pt-2">
                  <label className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-200">
                    Evaluation Notes & Strengths
                  </label>
                  <textarea
                    placeholder="Provide specific notes regarding resumes, strengths, weaknesses, and performance markers..."
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    rows={4}
                    className="w-full rounded-2xl border border-slate-200/80 bg-white p-3 text-xs text-slate-700 outline-none focus:border-indigo-500 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 focus:ring-1 focus:ring-indigo-500 transition-all resize-none"
                    required
                  />
                </div>
              </div>

              {/* Form Action Footer */}
              <div className="border-t border-slate-200/80 bg-slate-50 p-6 dark:border-slate-800 dark:bg-slate-950/60 flex items-center justify-between gap-3 shrink-0">
                <button
                  type="button"
                  onClick={onClose}
                  className="flex-1 h-10 border border-slate-200 rounded-xl bg-white text-xs font-bold text-slate-700 hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 dark:hover:bg-slate-900 transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex-1 h-10 rounded-xl bg-blue-600 text-xs font-bold text-white hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 transition-colors shadow-sm cursor-pointer"
                >
                  Submit Evaluation ({totalEarnedPoints.toFixed(1)} Pts)
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
